const esbuild = require('esbuild');
const { visualizer } = require('esbuild-visualizer');
const fs = require('fs');
const path = require('path');

const production = process.argv.includes('--production');
const watch = process.argv.includes('--watch');
const analyze = process.argv.includes('--analyze');

/**
 * Bundle analysis plugin
 * Generates visualizations using esbuild-visualizer
 * @type {import('esbuild').Plugin}
 */
const bundleAnalyzerPlugin = {
    name: 'bundle-analyzer',
    setup(build) {
        build.onEnd(async (result) => {
            if (!analyze || !result.metafile) {
                return;
            }

            try {
                // Generate visualizer HTML using esbuild-visualizer
                const html = await visualizer(result.metafile, {
                    title: 'Markdown Extended Pro - Bundle Analysis',
                    template: 'treemap' // 'sunburst', 'treemap', 'network'
                });
                
                // Write the HTML to file
                await fs.promises.writeFile('dist/bundle-stats.html', html);

                // Also generate simple text analysis
                const inputs = result.metafile.inputs;
                const analysis = {
                    bundleSize: 0,
                    modules: []
                };

                for (const [file, data] of Object.entries(inputs)) {
                    analysis.modules.push({
                        file,
                        bytes: data.bytes
                    });
                    analysis.bundleSize += data.bytes;
                }

                analysis.modules.sort((a, b) => b.bytes - a.bytes);

                console.log('\n✅ Bundle analysis complete!');
                console.log(`📊 Interactive visualization: dist/bundle-stats.html`);
                console.log(`📦 Total bundle size: ${formatBytes(analysis.bundleSize)}`);
                console.log(`🗂️  Modules: ${analysis.modules.length}`);
                console.log(`\n🔝 Top 10 largest modules:`);
                analysis.modules.slice(0, 10).forEach((mod, i) => {
                    console.log(`   ${(i + 1).toString().padStart(2)}. ${formatBytes(mod.bytes).padStart(10)} - ${mod.file}`);
                });
            } catch (error) {
                console.error('❌ Bundle analysis failed:', error.message);
            }
        });
    }
};

/**
 * Format bytes to human readable string
 */
function formatBytes(bytes) {
    if (bytes === 0) {
        return '0 B';
    }
    const k = 1024;
    const sizes = ['B', 'KB', 'MB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

/**
 * @type {import('esbuild').Plugin}
 */
const esbuildProblemMatcherPlugin = {
    name: 'esbuild-problem-matcher',

    setup(build) {
        build.onStart(() => {
            console.log('[watch] build started');
        });
        build.onEnd(result => {
            result.errors.forEach(({ text, location }) => {
                console.error(`✘ [ERROR] ${text}`);
                console.error(`    ${location.file}:${location.line}:${location.column}:`);
            });
            console.log('[watch] build finished');
        });
    }
};

async function main() {
    const ctx = await esbuild.context({
        entryPoints: ['src/extension.ts'],
        bundle: true,
        format: 'cjs',
        minify: production,
        sourcemap: !production,
        sourcesContent: false,
        platform: 'node',
        outfile: 'dist/extension.js',
        external: [
            'vscode',
            // Externalize all markdown-it plugins so they're loaded from node_modules at runtime
            'markdown-it-abbr',
            'markdown-it-attrs',
            'markdown-it-bracketed-spans',
            'markdown-it-checkbox',
            'markdown-it-container',
            'markdown-it-deflist',
            'markdown-it-emoji',
            'markdown-it-footnote',
            'markdown-it-html5-embed',
            'markdown-it-ib',
            'markdown-it-kbd',
            'markdown-it-mark',
            'markdown-it-multimd-table',
            'markdown-it-sub-alt',
            'markdown-it-sup-alt',
            'markdown-it-table-of-contents'
        ],
        logLevel: 'silent',
        metafile: analyze, // Enable metafile for analysis
        plugins: [
            esbuildProblemMatcherPlugin,
            ...(analyze ? [bundleAnalyzerPlugin] : [])
        ],
        // Node.js built-ins should be external
        // VS Code extensions run in Node.js environment
        define: {
            'process.env.NODE_ENV': production ? '"production"' : '"development"'
        },
        // Ensure proper handling of __dirname and __filename
        banner: {
            js: `
// VS Code Extension Bundled Entry
// This file was generated by esbuild
`.trim()
        }
    });

    if (watch) {
        await ctx.watch();
        console.log('Watching for changes...');
    } else {
        await ctx.rebuild();
        await ctx.dispose();
    }
}

main().catch(e => {
    console.error(e);
    process.exit(1);
});
